### PR TITLE
Add interrupt support & examples to MCP23017

### PR DESCRIPTION
**Pull request by ladyada**
this is for a gpio expander bonnet, can now manipulate the IRQ control registers. also set default to be IRQ pins are open drain.

### CODE REVIEW

**Comment by ladyada** [comment]
normally i wouldnt...i guess i could try to abstract em but it'd get really 'wordy' - this was to test a new hardware.

**Comment by tannewt** [comment]
+1 to renaming the properties to fully explain what they are. The comments are really handy so by renaming we'll remove any hint of data sheet-ism.

**Comment by ladyada** [comment]
but, they'd still need to be assigned and read as if they were the registers... zat ok?

**Comment by tannewt** [comment]
Sorry it took me a while to get back. 

Ya, I think it's fine that they are bitmasks. The documentation makes that clear. The fact that they map to a register under the hood isn't important though.

**Comment by ladyada** [comment]
added/updated!
take a look

**Comment by ladyada** [comment]
@tannewt ok im gonna merge this - next time i sweep thru this library ill update them to `register`s, i think perhaps this was written pre-`register`

**Pull request merged**
