### PR TITLE
Add INTCAP register access

### PR DESCRIPTION
**Pull request by flyte**
Add access to INTCAP registers in order to read the value of a pin at the point of interrupt.

### CODE REVIEW

**Comment by jposada202020** [comment]
@flyte I will have hardware to test this week, however I do have a question. I just need to call the property after library instantiation?

**Comment by flyte** [comment]
Yep, I think so. It's not exactly fresh in my mind any more though 😅

**Comment by jposada202020** [comment]
first of all I am sorry, but cmon is has been only 4 months 😄 . But I promise that I will test this week for sure ... If I remember .. 🤦🏼 😄 . now for real, hopefully hardware will be here by Thursday and I can test. Thanks again

**Review by jposada202020 — APPROVED** [review]
This was tested on
```python
Adafruit CircuitPython 7.0.0-alpha.2-608-gd134e2af8 on 2021-05-19; Adafruit Feather M4 CAN with same51j19a
```

using the following simplified test code
```python
>>> import board
>>> import digitalio
>>> from adafruit_mcp230xx.mcp23017 import MCP23017
>>> i2c = board.I2C()
>>> mcp = MCP23017(i2c)
>>> mcp.
iodir           gppu            iocon           _write_u16le
gpio            _read_u16le     gpioa           _read_u8
_write_u8       gpiob           iodira          iodirb
gppua           gppub           get_pin         ipol
ipola           ipolb           interrupt_configuration
interrupt_enable                default_value   io_control
int_flag        int_flaga       int_flagb       int_cap
int_capa        int_capb        clear_ints      clear_inta
clear_intb
>>> mcp.int_cap
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
>>> mcp.int_capa
[0, 0, 0, 0, 0, 0, 0, 0]
>>> mcp.int_capb
[0, 0, 0, 0, 0, 0, 0, 0]
```

Works as described. Thanks

**Comment by jposada202020** [comment]
Thanks sorry for the delay...

**Comment by flyte** [comment]
No worries! I didn't mean that you'd taken too long, just that my memory is terrible!

**Comment by jposada202020** [comment]
:) it is all good. Thanks again 👍🏼

**Pull request merged**
