### PR TITLE
Adding support for defining input pin polarity

### PR DESCRIPTION
**Pull request by shadowclaw**

### CODE REVIEW

**Comment by shadowclaw** [comment]
Not sure what is failing for whatever "black" is.

**Comment by FoamyGuy** [comment]
Hi there @shadowclaw thanks for working on this! 

Black is the python code formatter that we use on all of the code in the project. You can learn about how to use it to format the code here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/black

If you run black on the code files and then push a new commit it should resolve that actions check and let you get past it.

**Comment by shadowclaw** [comment]
Alright this should be good to go now.  Also this has been tested on hardware and confirmed to work.

**Review by FoamyGuy — APPROVED** [review]
I tested this successfully with a [Pi 16x2 LCD](https://www.adafruit.com/product/1110) with a modified version of [one of the examples](https://github.com/adafruit/Adafruit_CircuitPython_CharLCD/blob/master/examples/charlcd_keypad_simpletest.py). These changes don't interfere with anything in that example and the new invert_polarity parameter is working successfully to swap the value to opposite.

**Pull request merged**
